# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=5, null=True)),
                ('name', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(default='', max_length=100, null=True)),
                ('company_website', models.CharField(default='', max_length=1000, null=True)),
                ('mobile', models.CharField(default='', max_length=30, null=True)),
                ('designation', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=200)),
                ('user_to', models.CharField(max_length=200)),
                ('journey_date', models.DateField(default='')),
                ('boarding_point', models.CharField(max_length=200)),
                ('dropping_point', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=350)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('telephone_country_code', models.CharField(default='', max_length=10, null=True)),
                ('telephone', models.CharField(default='', max_length=10, null=True)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.AccountType')),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.CountryList')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.EmployeeJourney')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Employee')),
            ],
        ),
    ]
