# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telephone_country_code',
        ),
    ]
