# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180523_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emp',
            new_name='journey',
        ),
    ]
